import sys
sys.path.append('..')

import os
from tqdm import tqdm

from DomainPrediction.esm.esm2 import ESM2
from DomainPrediction.eval import metrics
from DomainPrediction.utils import helper

model_path = '/data/users/kgeorge/workspace/esm2/checkpoints/esm2_t33_650M_UR50D.pt'
esm2 = ESM2(model_path = model_path, device='gpu')

## for gxps seq reconstruction
p1 = "VCVHQLFEQQIEKTPDAIAVIYENQTLSYAELNARANRLAHQLIALGVAPDQRVAICVTRSLARIIGLLAVLKAGGAYVPLDPAYPGERLAYMLTDATPVILMADNVGRAALSEDILATLTVLDPNTLLEQPDHNPQVSGLTPQHLAYVIYTSGSTGRPKGVMIEHRSVVNLTLTQITQFDVCATSRMLQFASFGFDASVWEIMMALSCGAMLVIPTETVRQDPQRLWRYLEEQAITHACLTPAMFHDGTDLPAIAIKPTLIFAGEAPSPALFQALCSRADLFNAYGPTEITVCATTWDCPADYTGGVIPIGSPVANKRLYLLDEHRQPVPLGTVGELYIGGVGVARGYLNRPELTAERFLNDPFSDETNARMYRAGDLARYLPDGNLVFVGRNDQQVKIRGFRIEPGEIEARLVEHSEVSEALVLALGDGQDKRLVAYVVALADDGLATKLREHLSDILPDYMIPAAFVRLDAFPLTPNGKLDRRSLP"
p2 = "QAEIDRIVEQVPGGIANIQDIYALSPLQDGILFHHLLANEGDPYLLITQQAFADRPLLNRYLAAVQQVVDRHDILRTAFIWEGLSVPAQVICRQAPLSVTELTLNPADGAISNQLAQRFDPRRHRIDLNQAPLLRFVVAQESDGRWILLQLLHHLIGDHTTLEVMNSEVQACLLGQMDSLPAPVPFRHLVAQARQGVSQAEHTRFFTDMLAEVDEPTLLFGLAEAHHDGSQVTESHRMLTAGLNERLRGQARRLGVSVAALCHLAWAQVLSRTSGQTQVVFGTVLFGRMQAGEGSDSGMGLFINTLPLRLDIDNTPVRDSVRAAHSRLAGLLEHEHASLALAQRCSGVESGTPLFNALLNYRHNTQPVTPDEIVSGIEFLGAQERTNYPFVLSVEDSGSDLGLTAQVVQPFDPERICGYMQQALASLVQA"

fasta_path = '../../Data/round_1_exp/order-ESM3.fasta'
records = helper.read_fasta(fasta_path)
temp = []
for rec in records:
    perplexity = metrics.compute_perplexity(esm2, p1+str(rec.seq)+p2)
    print(f'{rec.id} : {perplexity}')
    temp.append(perplexity)

fasta_path = '../../Data/round_1_exp/order-MPNN.fasta'
records = helper.read_fasta(fasta_path)
for rec in records:
    perplexity = metrics.compute_perplexity(esm2, p1+str(rec.seq)+p2)
    print(f'{rec.id} : {perplexity}')
    temp.append(perplexity)

print(temp)